module.exports = {
  homeUrl: "https://vaithuhay.com/",
  productsUrl: "https://vaithuhay.com/collections/tatcasanpham",
  productDetailUrl: "https://vaithuhay.com/products",
  collectionUrl: "https://vaithuhay.com/collections",
  blogsUrl: "https://vaithuhay.com/blogs",
  checkoutsUrl:
    "https://vaithuhay.com/checkouts/b44f571d4f704838a2d22bde8a4ec795",
  productElement: {
    product: ".collection-pro",
    name: ".caption a h4",
    link: ".caption a",
    original_price: ".ega-compare-price",
    discounted_price: ".ega-price",
    image: ".vth-thumb a img",
    description: ".Kj.description",
  },
  productDetailElement: {
    title: ".Fb",
    origin: ".vendor-content p strong",
    long_description: ".vendor-content p",
    highlights: ".intro-info",
    name: ".intro-info h2",
    img: ".intro-img img",
    highlights_html: ".intro-info ul",
    specifications: ".product-specifications table tbody",
  },
  productDiscountsElement: {
    discount_value: "#variant_price",
  },
  productImagesElement: {
    listImage: ".product-images",
    mainImage: ".slick-current.slick-active img",
    subImage: ".content.gallery--onslide",
  },
  collectionsElement: {
    item: ".ega-item-sidebar",
    link: ".ega-item-sidebar a",
    subLink: ".ega-sidebar-submenu a",
    name: ".ega-item-sidebar a span",
    image: ".sidebar-icon-wrap img",
  },
  productVariantElement: {
    item: ".preorder-summary.vth-product-summary",
    name: "#idProduct",
    price: "#variant_price",
    image: ".slick-slide.slick-current.slick-active img",
    attributeValue: ".btn.btn-variant.option-main span",
    btnVariant: ".btn.btn-variant.option-main",
    attribute: ".option",
    variantContainer: ".preorder-row",
    optionContainer: ".product-variants.swatch-options",
  },
  blogProductsElement: {
    blogList: ".product-content",
    blogItem: ".ega-content-toggle:not(.product-tech-box)",
    title: ".ega-toggle-head ",
    contentHtml: ".ega-toggle-body .toggle-body-content",
  },
  vouchersElement: {
    btnOpenModule: ".hrv-discount-choose-coupons",
    listVouchers: ".hrv-discount-code-web",
    voucherItem: ".coupon_item",
    code: ".coupon_title span",
    description: ".coupon_desc",
  },
  blogSystemElement: {
    blogList: ".post-list .row",
    blogItem: ".col-md-4",
    slug: ".article-loop .img a",
    thumbnail: ".article-loop .img a img",
    title: ".description a h4",
    author: ".description p strong",
    contentHtml: ".article-main-content",
  },
};
