module.exports = {
  homeUrl: "https://vaithuhay.com",
  productsUrl: "https://vaithuhay.com/collections/tatcasanpham",
  productDetailUrl: "https://vaithuhay.com/products",
  collectionUrl: "https://vaithuhay.com/collections",
  blogsUrl: "https://vaithuhay.com/blogs",
  checkoutsUrl:
    "https://vaithuhay.com/checkouts/b44f571d4f704838a2d22bde8a4ec795",
  productElement: {
    product: ".collection-pro",
    price: ".variant_price",
    link: ".caption a",
    name: ".caption a h4",
    original_price: ".ega-compare-price",
    discounted_price: ".ega-price",
    image: ".vth-thumb a img",
    description: ".Kj.description",
  },
  productDetailElement: {
    title: ".Fb",
    origin: ".vendor-content p strong",
    long_description: ".vendor-content p",
    highlights: ".intro-info",
    name: ".intro-info h2",
    img: ".intro-img img",
    highlights_html: ".intro-info ul",
    specifications: ".product-specifications table tbody",
  },
  productDiscountsElement: {
    discount_value: "#variant_price",
  },
  productImagesElement: {
    listImage: ".product-images",
    mainImage: ".slick-current.slick-active img",
    subImage: ".content.gallery--onslide",
  },
  collectionsElement: {
    collectionList: "discovery__list",
    collectionItem: ".discovery__item",
  },
  productVariantElement: {
    item: ".preorder-summary.vth-product-summary",
    name: "#idProduct",
    price: "#variant_price",
    image: ".slick-slide.slick-current.slick-active img",
    attributeValue: ".btn.btn-variant.option-main span",
    btnVariant: ".btn.btn-variant.option-main",
    attribute: ".option",
    variantContainer: ".preorder-row",
    optionContainer: ".product-variants.swatch-options",
  },
  blogProductsElement: {
    blogList: ".product-content",
    blogItem: ".ega-content-toggle:not(.product-tech-box)",
    title: ".ega-toggle-head ",
    contentHtml: ".ega-toggle-body .toggle-body-content",
  },
  vouchersElement: {
    btnOpenModule: ".hrv-discount-choose-coupons",
    listVouchers: ".hrv-discount-code-web",
    voucherItem: ".coupon_item",
    code: ".coupon_title span",
    description: ".coupon_desc",
  },
  blogSystemElement: {
    blogList: ".post-list .row",
    blogItem: ".col-md-4",
    slug: ".article-loop .img a",
    thumbnail: ".article-loop .img a img",
    title: ".description a h4",
    author: ".description p strong",
    contentHtml: ".article-main-content",
  },
  comboElement: {
    container: ".container-gallery .slick-list .slick-track", // vào container
    containerItem: ".item-owl.slick-slide", // trong container có 44 item
    slideItem: ".slider-big",
    item: ".item-list.item-owl",
    groupHotSpots: ".group-btn-pro",
    containerIn4: ".group-detail",
    author: ".group-top .create-by strong",
    desc: ".group-bottom",
    product: ".collection-pro",
    name: ".caption a h4",
    price: ".variant_price",
    original_price: ".ega-compare-price",
    discounted_price: ".ega-price",
    image: ".vth-thumb a img",
    shortDesc: ".short-desc",
    detailDesc: ".detail-desc",
    description: ".Kj.description",
    productName: ".caption a h4",
  },
};
